name: update
description: A package for checking for updates.
homepage: https://github.com/Ampless/update

version: 0.3.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pub_semver: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  schttp: ^2.0.0
