name: update
description: A package for checking for updates.
version: 0.4.0
homepage: https://github.com/Ampless/update

environment:
  sdk: ^3.0.0

dependencies:
  pub_semver: ^2.0.0

dev_dependencies:
  lints: ^5.0.0
  schttp: ^5.0.0
  tested: ^1.0.0
